{% set name = "FLAML" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 91920acc46415940cfa50a2140f84af6cd38a7b747960c7e406af7e3106e2a68

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.16.2
    - lightgbm >=2.3.1
    - xgboost >=0.90,<=1.3.3
    - scipy >=1.4.1
    - pandas >=1.1.4
    - scikit-learn >=0.24
    - python >=3.6

test:
  requires:
    - pip
    - pytest
    - pandas >=1.1.4
    - scikit-learn >=0.24  
  source_files:    
    - test
    - pytest.ini
  commands:
    # - pytest test/conda -m conda
    - pytest test/nlp -k test_classification_head
    
about:
  home: https://github.com/microsoft/FLAML
  summary: A fast and lightweight autoML system
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:    
    - michalchromcak
    - shao-kun-zhang
