{% set name = "FLAML" %}
{% set version = "0.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8c5e593e011e875b7bad2fcee43078288abc8133e6eb8a566cd7ad80f4ccd231

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.16.2
    - lightgbm >=2.3.1
    - xgboost >=0.90,<=1.3.3
    - scipy >=1.4.1
    - pandas >=1.1.4
    - scikit-learn >=0.24
    - python >=3.6

test:  
  requires:
    - pip
    - pytest    
    - pandas >=1.1.4
    - scikit-learn >=0.24  
  files:
    - run_test.py
  commands:
    - pytest run_test.py
    

about:
  home: https://github.com/microsoft/FLAML
  summary: A fast and lightweight autoML system
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - michalchromcak
