{% set name = "flaml" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/FLAML-{{ version }}.tar.gz
  sha256: ba8b62df4f459e226f951e03c4238a699b3168f708e30c4e7c75eba261896fe2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # numpy 1.26.4(latest version <2.0) not avalible from py<39
  # pandas 1.5.3(latest version <2.0) not avaliable for py>311
  skip: True  # [py<39 or py>311]
  skip: True  # [s390x]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    # AttributeError: `np.Inf` was removed in the NumPy 2.0 release. Use `np.inf` instead.
    # Set last compatible version for NumPy
    - numpy >=1.17.0rc1,<=2.0
    - lightgbm >=2.3.1
    - scipy >=1.4.1
    - scikit-learn >=0.24
    # return klass(values, ndim=ndim, placement=placement, refs=refs)
    # TypeError: Argument 'placement' has incorrect type (expected pandas._libs.internals.BlockPlacement, got numpy.ndarray)
    # Set last compatible versions for xgboost and pandas <2.0
    - pandas >=1.1.4,<2.0
    - xgboost >=0.90,<2.0

# ModuleNotFoundError: No module named 'hcrystalball'
{% set deselect_tests = " --deselect=test/test_model.py::test_prep" %}
# Pkg vowpalwabbit is not created for the win platform
{% set deselect_tests = deselect_tests + " --deselect=test/test_autovw.py::TestAutoVW::test_vw_oml_problem_and_vanilla_vw" %}  # [win]

test:
  source_files:
    - test
  imports:
    - flaml
  commands:
    - pip check
    - pytest -v {{ deselect_tests }} test
  requires:
    - pip
    - pytest
    # In the snowflake channel avaliable only openml==0.12.2 (default is 0.10.2)
    - openml ==0.12.2
    - catboost
    # Pkg is not created for the win platform
    - vowpalwabbit  # [not win]

about:
  home: https://github.com/microsoft/FLAML
  summary: A fast and lightweight autoML system
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: https://github.com/microsoft/FLAML
  doc_url: https://microsoft.github.io/FLAML/
  description: FLAML is a lightweight Python library that finds accurate machine learning models automatically, efficiently and economically.

extra:
  recipe-maintainers:
    - michalchromcak
    - skzhang1
